services:
  postgres:
    container_name: bots-arena-db-compose
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: bots_arena
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "bots_arena"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


  backend:
    container_name: bots-arena-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:1234@postgres:5432/bots_arena
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
